server.address=0.0.0.0
server.port=8081
spring.application.name=auth-service

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true

# Connection Pooling (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=2000000

# LDAP Configuration
 spring.ldap.urls=${LDAP_SERVER_URL}
 spring.ldap.base=${LDAP_BASE_DN}
 spring.ldap.username=${LDAP_USERNAME}
 spring.ldap.password=${LDAP_BIND_PASSWORD}


spring.ldap.authentication.method=${LDAP_AUTH_METHOD}
spring.ldap.search.base=${LDAP_USER_SEARCH_BASE}
spring.ldap.search.filter=${LDAP_USER_SEARCH_FILTER}
spring.ldap.search.scope=${LDAP_SEARCH_SCOPE}


# JWT Configuration
jwt.secret=${JWT_SECRET_KEY}
jwt.access-expiration-ms=${JWT_ACCESS_TOKEN_EXPIRATION_MS}
jwt.expiration-ms=${JWT_TOKEN_EXPIRATION_MS}
jwt.refresh-expiration-ms=${JWT_REFRESH_TOKEN_EXPIRATION_MS}

# Mail Configuration
spring.mail.host=${MAIL_SMTP_HOST}
spring.mail.port=${MAIL_SMTP_PORT}
spring.mail.username=${MAIL_SMTP_USERNAME}
spring.mail.password=${MAIL_SMTP_PASSWORD}

#Logging Configuration
logging.level.org.springframework.ldap=DEBUG
logging.level.javax.naming=DEBUG

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.cloud.gateway=TRACE

