server.port=8082
spring.application.name=employee-service

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Connection Pooling (HikariCP)
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=2000000

# LDAP Configuration
spring.ldap.urls=ldap://4.178.121.186:389
spring.ldap.base=dc=otbs,dc=local
spring.ldap.username=CN=wael,CN=Users,DC=otbs,DC=local
spring.ldap.password=7Anoutlolowaelwael


spring.ldap.authentication.method=${LDAP_AUTH_METHOD}
spring.ldap.search.base=${LDAP_USER_SEARCH_BASE}
spring.ldap.search.filter=${LDAP_USER_SEARCH_FILTER}
spring.ldap.search.scope=${LDAP_SEARCH_SCOPE}

#Logging Configuration

# JWT Configuration
jwt.secret=${JWT_SECRET_KEY}
jwt.access-expiration-ms=${JWT_ACCESS_TOKEN_EXPIRATION_MS}
jwt.expiration-ms=${JWT_TOKEN_EXPIRATION_MS}
jwt.refresh-expiration-ms=${JWT_REFRESH_TOKEN_EXPIRATION_MS}

feign.client.config.default.loggerLevel=full
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000
feign.client.config.default.retryer.period=1000
feign.client.config.default.retryer.maxPeriod=5000
feign.client.config.default.retryer.maxAttempts=3


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
